contacts_app/urls.py
from django.urls import path
from . import views

app_name = 'contacts_app'

urlpatterns = [
    path('view_profile/<int:user_id>', views.view_profile, name='view_profile'),
    path('view_friends', views.view_friends, name='view_friends'),
    path('view_users', views.view_users, name='view_users'),
    path('send_request/<int:user_id>/', views.send_request, name='send_request'),
    path('accept_request/<int:request_id>/', views.accept_request, name='accept_request'),
    path('reject_request/<int:request_id>/', views.reject_request, name='reject_request'),
    path('cancel_friend_request/<int:to_user_id>/', views.cancel_friend_request, name='cancel_friend_request'),
    path('remove_friend/<int:friend_id>/', views.remove_friend, name='remove_friend'),
]

main/urls.py
from .views import *
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
]

posts_app/urls.py
from .  import views
from django.urls import path

app_name = 'posts_app'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('post/<slug:slug>', views.post_page, name = "page"),
    path('my_posts', views.my_posts, name = 'my_posts'),
    path('my_posts/<int:post_id>', views.delete_post, name = 'delete_post'),
    path('new_post', views.new_post, name='new_post'),
    path('my_posts/update/<int:id>', views.update_post, name='update_post'),
    path('posts_commented', views.posts_commented, name='posts_commented'),
    path('update_comment/<int:comment_id>/<slug:slug>', views.update_comment, name='update_comment'),
    path('delete_comment/<int:comment_id>/<slug:slug>', views.delete_comment, name = 'delete_comment'),
    path('like_post/<int:post_id>', views.like_post, name = 'like'),
    path('like_post_commented/<int:post_id>', views.like_post_commented, name = 'like_commented'),
    ]

social_media_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('users_app.urls')),
    path('posts/', include('posts_app.urls')),
    path('profile/', include('profile_app.urls')),
    path('contacts/', include('contacts_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()    
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='post_images/', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name='posts')

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-date'] 

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None, related_name="post_comments" )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "user_comments")
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return  self.author.username + "'s comment on " + self.post.title + " by " + self.post.author.username

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None, related_name="post_likes" )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "user_likes")

posts_app/models.py
from django.db import models

# Create your models here.

posts_app/forms.py
from django import forms
from main.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','body','image']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter post title'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter post content'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

posts_app/views.py
from django.shortcuts import render, redirect
from main.models import Post, Comment, Like
from profile_app.models import Profile
from django.contrib.auth.decorators import login_required
from .forms import PostForm
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.urls import reverse


# Create your views here.
@login_required
def all_posts(request):
    posts = Post.objects.all()
    num_comments = [len(post.post_comments.all()) for post in posts]
    num_likes = [len(post.post_likes.all()) for post in posts]
    profile = Profile.objects.get(user=request.user)
    return render(request, 'posts_app/all_posts.html', {'posts': posts, 'profile': profile,
                                                        'num_comments': num_comments, 'num_likes': num_likes})


@login_required
def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    comments = Comment.objects.filter(post_id=post.id)
    profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        body = request.POST.get('body')
        new_comment = Comment.objects.get_or_create(post = post, author = request.user, body=body)[0]
        new_comment.save()          
    return render(request, 'posts_app/post_page.html', {'post':post, 'post_id': post.id,
                                                        'comments': comments, 'profile': profile})


@login_required
def update_comment(request, comment_id, slug):
    comment = Comment.objects.get(id=comment_id)
    if request.method == 'POST':
        body = request.POST.get('body')
        comment.body = body
        comment.save()
        return redirect('posts_app:page', slug=slug)
    else :
        return render(request, 'posts_app:page', slug=slug)
    
@login_required
def delete_comment(request, comment_id, slug):
    if request.method == 'POST':
        comment = Comment.objects.get(id=comment_id)
        comment.delete()
        return redirect('posts_app:page', slug=slug)
    else :
        return render(request, 'posts_app:page', slug=slug)
       


@login_required
def my_posts(request):
    user = request.user
    posts = user.posts.all()
    num_comments = [len(post.post_comments.all()) for post in posts]
    num_likes = [len(post.post_likes.all()) for post in posts]

    profile = Profile.objects.get(user=request.user)
    return render(request, 'posts_app/my_posts.html', {'posts':posts, 'profile': profile, 
                                                       'num_comments': num_comments, 'num_likes':num_likes})

@login_required
def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    user = request.user
    posts = user.posts.all()
    profile = Profile.objects.get(user=request.user)
    return render(request, 'posts_app/my_posts.html', {'posts':posts, 'profile': profile })

@login_required
def new_post(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.slug = slugify(post.title)
            post.save()
            return redirect('posts_app:my_posts')
    else:
        form = PostForm()

    return render(request, 'posts_app/new_post.html', {'form': form, 'profile': profile})


@login_required
def update_post(request, id):
    profile = Profile.objects.get(user=request.user)
    post = Post.objects.get(id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts_app:my_posts')
    else:
        form = PostForm(instance=post)
    return render(request, 'posts_app/update_post.html', {'form': form, 'profile': profile})

@login_required
def posts_commented(request):
    usr = request.user
    user_comments = usr.user_comments.all()
    posts_ids = list(dict.fromkeys([comment.post.id for comment in user_comments]))
    posts = [Post.objects.get(id=id) for id in posts_ids]
    num_comments = [len(post.post_comments.all()) for post in posts]
    num_likes = [len(post.post_likes.all()) for post in posts]
    profile = usr.profile
    return render(request, 'posts_app/posts_commented.html', {'posts': posts, 'profile': profile, 
                                                              'num_comments': num_comments, 'num_likes': num_likes})

@login_required
def like_post(request, post_id):
    if request.method == 'POST':
        usr = request.user
        post = Post.objects.get(id=post_id)
        if len(post.post_likes.all().filter(user=usr).all())==0:
            like = Like(user = request.user, post = post)
            like.save()
            return redirect(reverse('posts_app:all_posts')+f'#post_{post_id}')
        else :
            return redirect(reverse('posts_app:all_posts')+f'#post_{post_id}')
        
@login_required
def like_post_commented(request, post_id):
    if request.method == 'POST':
        usr = request.user
        post = Post.objects.get(id=post_id)
        if len(post.post_likes.all().filter(user=usr).all())==0:
            like = Like(user = request.user, post = post)
            like.save()
            return redirect(reverse('posts_app:posts_commented')+f'#post_{post_id}')
        else :
            return redirect(reverse('posts_app:posts_commented')+f'#post_{post_id}')

posts_app/templates/posts_app/all_posts.html
{% extends "base.html" %}
{% load return_item %}
{% load social_share %}
{% block title %}All Posts{% endblock %}

{% block content %}
<div class="container py-4">
    <div class="row">
        <div class="col-12 col-xl-8 mx-auto">
            {% if posts %}
                {% for post in posts %}
                <a class="btn" href="#post_{{post.id}}"></a>
                <div id="post_{{post.id}}" class="card mb-4 shadow-sm">
                    <div class="card-header bg-white d-flex align-items-center gap-3 py-3">
                        <img src="{{ post.author.profile.profile_pic_url }}" 
                             class="rounded-circle border border-2 border-primary" 
                             alt="User" 
                             style="object-fit: cover; width: 60px; height: 60px;">
                        <div>
                           <a style="text-decoration: none;" href="{% url 'contacts_app:view_profile' post.author.profile.user.id %}"><h6 class="mb-1 text-capitalize fw-bold">{{ post.author }}</h6></a>
                            <small class="text-muted">{{ post.date|date:"F d, Y" }}</small>
                        </div>
                    </div>

                    <div class="card-body">
                        <h4 class="card-title mb-3">
                            <a href="{% url 'posts_app:page' slug=post.slug %}" 
                               class="text-dark text-decoration-none">{{ post.title }}</a>
                        </h4>

                        <a href="{% url 'posts_app:page' slug=post.slug %}" 
                           class="text-decoration-none text-dark">
                            <p class="card-text text-muted mb-3">
                                {{ post.body|truncatewords:30 }}
                            </p>
                        </a>

                        {% if post.image %}
                        <a href="{% url 'posts_app:page' slug=post.slug %}" class="shadow-none d-block mb-3">
                            <img src="{{ post.image.url }}" 
                                 class="img-fluid rounded-3" 
                                 alt="{{ post.title }}">
                        </a>
                        {% endif %}

                        <hr class="my-3">

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex align-items-center gap-2 text-muted">
                                <i class="fas fa-thumbs-up text-primary"></i>
                                <small>{{ num_likes|return_item:forloop.counter }} Likes</small>
                            </div>
                            <div>
                                <a href="{% url 'posts_app:page' slug=post.slug %}" 
                                   class="text-muted text-decoration-none">
                                    <small>
                                        {{ num_comments|return_item:forloop.counter }} Comments
                                    </small>
                                </a>
                            </div>
                        </div>

                        <hr class="my-3">

                        <div class="d-flex gap-2">
                            <form action="{% url 'posts_app:like' post.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-light text-muted  btn-sm d-flex align-items-center gap-2">
                                <i class="fas fa-thumbs-up"></i>
                                <span>Like</span>
                                </button>
                            </form>
                            <a href="{% url 'posts_app:page' slug=post.slug %}" 
                               class="btn btn-light text-muted  btn-sm d-flex align-items-center gap-2">
                                <i class="fas fa-comment"></i>
                                <span>Comment</span>
                            </a>
                            <button class="btn btn-light text-muted  btn-sm d-flex align-items-center gap-2">
                                <i class="fas fa-share-alt"></i>
                                <!--<span><a style="text-decoration: none; color:gray" href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
                                    Facebook</a></span>-->
                                <span>{% post_to_facebook object_or_url "Facebook" %}</span>
                            </button>
                            {% comment %} <button class="btn btn-light text-muted  btn-sm d-flex align-items-center gap-2">
                                <i class="fas fa-share-alt"></i>
                                <!--<span><a style="text-decoration: none; color:gray" href="https://twitter.com/home?status=I'm%20going%20to%20learn%20to%20Code...%20Come%20build%20an%20web%20apsp%20with%20me!%20%23CFE%20and%20@justinmitchel%20{{request.build_absolute_uri}}">
                                    X</a></span>-->
                                <span>{% post_to_twitter "{{post.title}} {{post.body}}" object_or_url "X" %}</span>
                            </button> {% endcomment %}
                        </div>
                    </div>
                </div>
                {% endfor %}

                {% if posts.has_other_pages %}
                <nav aria-label="Page navigation" class="mt-4">
                    <ul class="pagination justify-content-center">
                        {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
                        </li>
                        {% endif %}

                        {% for num in posts.paginator.page_range %}
                            {% if posts.number == num %}
                                <li class="page-item active">
                                    <span class="page-link">{{ num }}</span>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}

            {% else %}
                <div class="alert alert-info text-center" role="alert">
                    <i class="fas fa-info-circle me-2"></i>
                    No posts to display
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

posts_app/templates/posts_app/my_posts.html
{% extends "base.html" %}
{% load return_item %}
{% block title %}My posts{% endblock %}

{% block content %}
<div class="container py-4">
    <div class="row">
        <div class="col-12 col-xl-8 mx-auto">
            <div class="d-flex justify-content-center mb-4">
                <a href="{% url 'posts_app:new_post' %}" class="text-decoration-none btn btn-primary">
                    <i class="fas fa-plus me-2"></i> New Post
                </a>
            </div>

            {% if posts %}
                {% for post in posts %}
                <div class="card mb-4 shadow-sm">
                    <div class="card-header bg-white d-flex align-items-center gap-3 py-3">
                        <img src="{{ profile.profile_pic_url }}" 
                             class="rounded-circle border border-2 border-primary" 
                             alt="User" 
                             style="object-fit: cover; width: 60px; height: 60px;">
                        <div>
                            <h6 class="mb-1 text-capitalize fw-bold">{{ post.author }}</h6>
                            <small class="text-muted">{{ post.date|date:"F d, Y" }}</small>
                        </div>
                    </div>

                    <div class="card-body">
                        <h4 class="card-title mb-3">
                            <a href="{% url 'posts_app:page' slug=post.slug %}" class="text-dark text-decoration-none">{{ post.title }}</a>
                        </h4>

                        <a href="{% url 'posts_app:page' slug=post.slug %}" class="text-decoration-none text-dark">
                            <p class="card-text text-muted mb-3">
                                {{ post.body|truncatewords:30 }}
                            </p>
                        </a>

                        {% if post.image %}
                        <a href="{% url 'posts_app:page' slug=post.slug %}" class="shadow-none d-block mb-3">
                            <img src="{{ post.image.url }}" 
                                 class="img-fluid rounded-3" 
                                 alt="{{ post.title }}">
                        </a>
                        {% endif %}
                    </div>

                    <div class="card-footer bg-white">
                        <div class="d-flex justify-content-between">
                            <div class="d-flex align-items-center gap-2 text-muted">
                                <i class="fas fa-thumbs-up text-primary"></i>
                                <small>{{ num_likes|return_item:forloop.counter }} Likes</small>
                            </div>
                            <div>
                                <a href="{% url 'posts_app:page' slug=post.slug %}" 
                                   class="text-muted text-decoration-none">
                                    <small>{{ num_comments|return_item:forloop.counter }} Comments</small>
                                </a>
                            </div>
                        </div>

                        {% if user == post.author %}
                        <div class="mt-4 d-flex gap-2 justify-content-end">
                             <form action="{% url 'posts_app:update_post' post.id %}" method="get" class="m-0">
                                <button type="submit" class="btn btn-light btn-sm d-flex align-items-center gap-2">
                                 Edit
                                </button>
                            </form>
                            <form id="delete-form-{{ post.id }}" action="{% url 'posts_app:delete_post' post.id %}" method="post" class="m-0">
                                {% csrf_token %}
                                <button type="button" class="btn btn-light btn-sm d-flex align-items-center gap-2" onclick="confirmDelete('{{ post.id }}')">
                                   Delete
                                </button>
                            </form>
                        </div>
                        
                        {% endif %}
                    </div>
                </div>
                {% endfor %}

                {% if posts.has_other_pages %}
                <nav aria-label="Page navigation" class="mt-4">
                    <ul class="pagination justify-content-center">
                        {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
                        </li>
                        {% endif %}

                        {% for num in posts.paginator.page_range %}
                            {% if posts.number == num %}
                                <li class="page-item active">
                                    <span class="page-link">{{ num }}</span>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}

            {% else %}
            <div class="alert alert-info text-center" role="alert">
                <i class="fas fa-info-circle me-2"></i>
                No posts to display
            </div>
            {% endif %}
        </div>
    </div>
</div>

<script>
    function confirmDelete(postId) {
        const confirmed = confirm("Are you sure you want to delete this post?");
        if (confirmed) {
            document.getElementById(`delete-form-${postId}`).submit();
        }
    }
</script>

{% endblock %}

posts_app/templates/posts_app/new_post.html
{% extends "base.html" %}
{% load return_item %}

{% block title %}New Post{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center mb-4">New Post</h1>
            <form method="POST" enctype="multipart/form-data" class="bg-white">
                {% csrf_token %}
                 <div class="mb-3">
                    <label for="id_title" class="form-label">Title</label>
                    {{ form.title }}
                    {% if form.title.errors %}
                        <div class="text-danger small">{{ form.title.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_body" class="form-label">Body</label>
                    {{ form.body }}
                    {% if form.body.errors %}
                        <div class="text-danger small">{{ form.body.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_image" class="form-label">Image</label>
                    {{ form.image }}
                    {% if form.image.errors %}
                        <div class="text-danger small">{{ form.image.errors }}</div>
                    {% endif %}
                </div>
                <div class="d-flex gap-2">
                    <button type="submit" class="btn btn-primary">Publish</button>
                    <a href="{% url 'posts_app:my_posts' %}" class="btn btn-outline-primary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

posts_app/templates/posts_app/post_page.html
{% extends "base.html" %}
{% block title %} {{ post.title }} {% endblock %}
{% block content %}
<div class="container py-4">
  <div class="content-wrapper mx-auto" style="max-width: 800px">
    <div class="row mb-4">
      <div class="col-12">
        <h2 class="display-6 text-dark fw-semibold mb-3">{{ post.title }}</h2>
      </div>
    </div>

    <div class="row g-4 mb-4">
      {% if post.image %}
      <div class="col-12">
        <img
          class="img-fluid rounded-3 shadow-sm"
          src="{{ post.image.url }}"
          alt="{{ post.title }}"
        />
      </div>
      {% endif %}

      <div class="col-12">
        <div class="d-flex align-items-center gap-3 bg-light p-3 rounded-3">
          <img
            src="{{ post.author.profile.profile_pic_url }}"
            class="rounded-circle border border-2 border-primary"
            alt="User"
            style="object-fit: cover; width: 70px; height: 70px"
          />
          <div>
            <h5 class="mb-1 text-capitalize fw-bold">{{ post.author }}</h5>
            <small class="text-muted">Published on {{ post.date|date:"F d, Y" }}</small>
          </div>
        </div>
      </div>
    </div>

    <div class="row mb-5">
      <div class="col-12">
        <p class="lead text-dark">{{ post.body }}</p>
      </div>
    </div>

    <div class="row mb-4">
      <div class="col-12">
        <h4 class="border-bottom pb-2 mb-4">Comments ({{ comments.count }})</h4>

        {% for comment in comments %}
        <div
          class="card mb-3 bg-light  {% if comment.author == profile.user %}border-primary{% endif %}"
        >
          <div class="card-body d-flex gap-3">
            <img
              src="{{ comment.author.profile.profile_pic_url }}"
              class="rounded-circle"
              alt="User"
              style="width: 50px; height: 50px; object-fit: cover"
            />

            <div class="w-100">
              <div
                class="d-flex justify-content-between align-items-center mb-2"
              >
                <h6 class="mb-0 text-capitalize">{{ comment.author }}</h6>
                <small class="text-muted">{{ comment.date|timesince }} ago</small>
              </div>

              <p class="card-text border p-2 rounded bg-white" id="insert-form{{forloop.counter}}">
                {{ comment.body }}
              </p>

              {% if comment.author == profile.user %}
              <div class="d-flex gap-2 justify-content-end ">
                <!-- Pass the URL directly from Django template context -->
                <div id="edit-btn{{forloop.counter}}">
                <button
                  class="btn btn-sm btn-light"
                  id="add-form{{forloop.counter}}">
                  Edit
                </button>
                </div>
                <form
                  id="delete-form-{{forloop.counter}}"
                  action="{% url 'posts_app:delete_comment' comment.id comment.post.slug %}"
                  method="post"
                  class="d-inline"
                >
                  {% csrf_token %}
                  <button
                    type="button"
                    value="delete1"
                    class="btn btn-sm btn-light"
                    onclick="confirmDelete('{{forloop.counter}}')"
                  >
                    Delete
                  </button>
                </form>
                <script>
                  function confirmDelete(loopCounter) {
                      const confirmed = confirm("Are you sure you want to delete this comment?");
                      if (confirmed) {
                          document.getElementById(`delete-form-${loopCounter}`).submit();
                      }
                  }
                  document.getElementById('add-form{{forloop.counter}}').addEventListener("click", function () {
                      document.getElementById("insert-form{{forloop.counter}}").innerHTML=
                      `<form action="{% url 'posts_app:update_comment' comment.id comment.post.slug %}" method="post">
                          {% csrf_token %}
                          <div class="mb-3">
                          <textarea class="form-control" name="body" rows="4" required>{{comment.body}}</textarea>
                          </div>
                          <div class='d-flex gap-2 justify-content-end '>
                          <button type="submit" class="btn btn-primary btn-sm">Save</button>
                            <button
                    type="button"
                    value="delete"
                    class="btn btn-sm btn-outline-primary"
                    onclick="confirmDelete('{{forloop.counter}}')"
                  >
                    Delete
                  </button>
                          </div>
                          
                      </form>`;
                      document.getElementById("edit-btn{{forloop.counter}}").innerHTML=``;
                      document.querySelector('button[value="delete1"]').remove();
                  })
              </script>
              </div> 
            
                    
              {% endif %}
            </div>
          </div>
        </div>
        {% empty %}
        <div class="alert alert-info text-center" role="alert">
          No comments yet. Be the first to comment!
        </div>
        {% endfor %}
      </div>
    </div>

    {% if user.is_authenticated %}
    <div class="card mt-4">
      <div class="card-header">
        <h5 class="mb-0">Add a Comment</h5>
      </div>
      <div class="card-body">
        <form action="{% url 'posts_app:page' slug=post.slug %}" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <textarea
              class="form-control"
              name="body"
              rows="4"
              placeholder="Write your comment here..."
              required
            ></textarea>
          </div>
          <div class="d-flex gap-2">
            <button type="submit" class="btn btn-primary">
              <i class="bi bi-send me-2"></i>Submit Comment
            </button>
            <a
              href="{% url 'posts_app:my_posts' %}"
              class="btn btn-outline-primary"
              >Cancel</a
            >
          </div>
        </form>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %} 