contacts_app/urls.py
from django.urls import path
from . import views

app_name = 'contacts_app'

urlpatterns = [
    path('view_profile/<int:user_id>', views.view_profile, name='view_profile'),
    path('view_friends', views.view_friends, name='view_friends'),
    path('view_users', views.view_users, name='view_users'),
    path('send_request/<int:user_id>/', views.send_request, name='send_request'),
    path('accept_request/<int:request_id>/', views.accept_request, name='accept_request'),
    path('reject_request/<int:request_id>/', views.reject_request, name='reject_request'),
    path('cancel_friend_request/<int:to_user_id>/', views.cancel_friend_request, name='cancel_friend_request'),
    path('remove_friend/<int:friend_id>/', views.remove_friend, name='remove_friend'),
]

main/urls.py
from .views import *
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
]

posts_app/urls.py
from .  import views
from django.urls import path

app_name = 'posts_app'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('post/<slug:slug>', views.post_page, name = "page"),
    path('my_posts', views.my_posts, name = 'my_posts'),
    path('my_posts/<int:post_id>', views.delete_post, name = 'delete_post'),
    path('new_post', views.new_post, name='new_post'),
    path('my_posts/update/<int:id>', views.update_post, name='update_post'),
    path('posts_commented', views.posts_commented, name='posts_commented'),
    path('update_comment/<int:comment_id>/<slug:slug>', views.update_comment, name='update_comment'),
    path('delete_comment/<int:comment_id>/<slug:slug>', views.delete_comment, name = 'delete_comment'),
    path('like_post/<int:post_id>', views.like_post, name = 'like'),
    path('like_post_commented/<int:post_id>', views.like_post_commented, name = 'like_commented'),
    ]

social_media_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('users_app.urls')),
    path('posts/', include('posts_app.urls')),
    path('profile/', include('profile_app.urls')),
    path('contacts/', include('contacts_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q

# Create your models here.

class Friendship(models.Model):
    user1 = models.ForeignKey(User, related_name='friendships_as_user1', on_delete=models.CASCADE)
    user2 = models.ForeignKey(User, related_name='friendships_as_user2', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
            constraints = [
                models.UniqueConstraint(
                    fields=['user1', 'user2'],
                    name='unique_friendship'
                )
            ]
    
    def __str__(self):
        return f"{self.user1.username} - {self.user2.username}"
    
    
    def save(self, *args, **kwargs):
        if self.user1.id > self.user2.id:
            self.user1, self.user2 = self.user2, self.user1
        super().save(*args, **kwargs)



class FriendshipRequest(models.Model):
    from_user = models.ForeignKey(User, related_name='sent_friend_requests', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='received_friend_requests', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(default='pending',max_length=10)

    class Meta:
        unique_together = ('from_user', 'to_user')


    def __str__(self):
        return f"{self.from_user.username} -> {self.to_user.username} ({self.status})"

    
    def accept(self):
        friend_request = FriendshipRequest.objects.get(from_user=self.from_user, to_user=self.to_user)
        friend_request.delete()

        friendship = Friendship(user1=self.from_user, user2=self.to_user)
        friendship.save()


    def reject(self):
        self.delete()

    
    @staticmethod
    def are_friends(user1, user2):
        return Friendship.objects.filter(
            (Q(user1=user1) & Q(user2=user2)) | 
            (Q(user1=user2) & Q(user2=user1))
        ).exists()
    
    
    def friendship_status(user1, user2):
        try:            
            friend_request = FriendshipRequest.objects.get(from_user=user1, to_user=user2)
            return friend_request.status, friend_request.id
        
        except FriendshipRequest.DoesNotExist:
            try:
                friend_request = FriendshipRequest.objects.get(from_user=user2, to_user=user1)
                return "requested", friend_request.id
            
            except FriendshipRequest.DoesNotExist:
                return None, None
        

    

contacts_app/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.models import User

from .services import send_friend_request, accept_friend_request, reject_friend_request
from .models import Friendship, FriendshipRequest



# Create your views here.
@login_required
def view_profile(request, user_id):
    user = get_object_or_404(User, id=user_id)

    if request.user == user:
        return redirect('profile_app:profile')
    
    friendship_status, request_id = FriendshipRequest.friendship_status(request.user, user)
    is_friend = FriendshipRequest.are_friends(request.user, user)

    user_info = {'user': user,
                'profile': user.profile,
                'is_friend': is_friend, 
                'friendship_status': friendship_status, 
                'request_id': request_id,
                }

    return render(request, 'contacts_app/view_profile.html', {'user_info': user_info, 'profile': request.user.profile})


@login_required
def view_users(request):
    users_info_list = []
    users = User.objects.exclude(id=request.user.id).order_by('-date_joined')

    for user in users:
        is_friend = FriendshipRequest.are_friends(request.user, user)
        friendship_status, request_id = FriendshipRequest.friendship_status(request.user, user)
        users_info_list.append({'user': user,
                                'profile': user.profile,
                                'is_friend': is_friend,
                                'friendship_status': friendship_status,
                                'request_id': request_id})
    
    return render(request, 'contacts_app/view_users.html', {'users_info_list': users_info_list, 'profile': request.user.profile})


@login_required
def view_friends(request):
    user = request.user
    users_info_list = []

    friend_requests_queryset = FriendshipRequest.objects.filter(to_user=user)
    friend_requests = [request.from_user for request in friend_requests_queryset]
    friends = list(user.profile.friends)

    users = friend_requests + friends
    
    for user in users:
        is_friend = FriendshipRequest.are_friends(request.user, user)
        friendship_status, request_id = FriendshipRequest.friendship_status(request.user, user)
        users_info_list.append({
            'user': user,
            'profile': user.profile,
            'is_friend': is_friend,
            'friendship_status': friendship_status,
            'request_id': request_id
        })


    return render(request, 'contacts_app/view_friends.html', {'users_info_list': users_info_list, 'profile': request.user.profile})


@login_required
def send_request(request, user_id):
    to_user = get_object_or_404(User, id=user_id)

    message = send_friend_request(request.user, to_user)

    next_url = request.POST.get('next', '/')
    return redirect(next_url)


@login_required
def accept_request(request, request_id):
    message = accept_friend_request(request_id)
    next_url = request.POST.get('next', '/')
    return redirect(next_url)


@login_required
def reject_request(request, request_id):
    message = reject_friend_request(request_id)
    next_url = request.POST.get('next', '/')
    return redirect(next_url)


def cancel_friend_request(request, to_user_id):
    from_user = request.user
    to_user = User.objects.get(id=to_user_id)
    profile = to_user.profile
    
    try:
        friend_request = FriendshipRequest.objects.get(from_user=from_user, to_user=to_user, status='pending')
        friend_request.delete()
        next_url = request.POST.get('next', '/')
        return redirect(next_url)  
    
    except FriendshipRequest.DoesNotExist:
        return HttpResponse("The friend request was not found or has already been accepted/rejected.")


def remove_friend(request, friend_id):
    
    try:
        friend_to_remove = User.objects.get(id=friend_id)
        friendship = Friendship.objects.get(
            Q(user1=request.user, user2=friend_to_remove) | Q(user1=friend_to_remove, user2=request.user)
        )
        friendship.delete()

        next_url = request.POST.get('next', '/')
        return redirect(next_url, user_id=friend_id)
    
    except Friendship.DoesNotExist:
        return HttpResponse("Friendship record not found.")

contacts_app/templates/contacts_app/contacts.html
<!-- send request -->
<form method="post" action="{% url 'send_request' user.id %}">
    {% csrf_token %}
    <button type="submit">Add to friends</button>
</form>

<!-- Accept/reject -->
{% for request in user.received_friend_requests.all %}
    <p>{{ request.from_user.username }} wants to add you as a friend.</p>
    <form method="post" action="{% url 'accept_request' request.id %}">
        {% csrf_token %}
        <button type="submit">Accept</button>
    </form>
    <form method="post" action="{% url 'reject_request' request.id %}">
        {% csrf_token %}
        <button type="submit">Reject</button>
    </form>
{% endfor %}

contacts_app/templates/contacts_app/send_request.html
{% extends "base.html" %} 
{% block title %}Send Request{% endblock %} 
{% block content %}
<h3>{{ message }}</h3>

{% endblock %}

contacts_app/templates/contacts_app/view_friends.html
{% extends 'base.html' %}

{% block title %} Friends {% endblock %}

{% block content %}
<div class="container mt-4">
  {% if users_info_list %}
    <div class="row">
      {% for user_info in users_info_list %}
        <div class="col-12 col-md-6 col-lg-4 mb-4"> 
          <div class="card shadow-sm">
            <div class="card-body text-center">
   
              <img
                src="{{ user_info.profile.profile_pic_url }}"
                alt="Profile Picture"
                class="rounded-circle mb-3"
                style="width: 80px; height: 80px; object-fit: cover"
              />


              <h2 class="card-title text-primary text-capitalize mb-0">
                <a style="text-decoration: none;" href="{% url 'contacts_app:view_profile' user_info.user.id %}">{{ user_info.user.username }}</a>
              </h2>


              {% if user_info.friendship_status == 'requested' %}
                <div>
                  <span style="color:green">Sends you a friend request</span>

                  <div class="btn-group mt-3 mb-2 w-100 gap-2">
                    <form method="post" action="{% url 'contacts_app:accept_request' user_info.request_id %}" style="display: inline-block; width: 50%;">
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ request.path }}">
                      <button class="btn btn-success w-100" type="submit">Accept</button>
                    </form>

                    <form method="post" action="{% url 'contacts_app:reject_request' user_info.request_id %}" style="display: inline-block; width: 50%;">
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ request.path }}">
                      <button class="btn btn-danger w-100" type="submit">Reject</button>
                    </form>
                  </div>
                </div>

              {% elif user_info.is_friend %}
              <span style="color: transparent;">....</span>

                <div class="btn-group mt-3 mb-2 w-100 gap-2">
                  
                  <form method="POST" style="display: inline-block; width: 50%;">
                    {% csrf_token %}
                    <button class="btn btn-primary w-100" type="submit" disabled> Message</button>
                  </form>
                  <form method="POST" style="display: inline-block; width: 50%;" action="{% url 'contacts_app:remove_friend' user_info.user.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="btn btn-danger  w-100" type="submit">Remove </button>
                  </form>
                </div>

                <div>
                  
                </div>

              {% endif %}
              
            </div>
          </div>
        </div>
      {% endfor %}
      
    </div>
  {% else %}
    <div class="alert alert-info text-center" role="alert">
      <i class="fas fa-info-circle me-2"></i>
      No friends to display
    </div>
  {% endif %}
  <div class=" text-center">
    <a href="{% url 'posts_app:all_posts' %}" class="btn w-25 btn-secondary 0">
      Back
    </a>
  </div> 
</div>
{% endblock %}

contacts_app/templates/contacts_app/view_profile.html
{% extends "base.html" %} 
{% block title %}Show Profile{% endblock %} 
{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-body text-center">
          <h2 class="py-4">User Profile</h2>

          <img
            src="{{ user_info.profile.profile_pic_url }}"
            alt="Profile Picture"
            class="rounded-circle mb-3"
            style="width: 120px; height: 120px; object-fit: cover"
          />

          <p class="text-muted m-0" style="font-size: 14px">Username</p>
          <h2 class="card-title text-primary mb-0">
            {{ user_info.user.username }}
          </h2>

          <div class="text-start py-2">
            <div class="d-flex gap-4 border-bottom pb-2">
              <strong>Joined:</strong>
              <span class="text-muted ms-1">
                {{ user_info.user.date_joined }}
              </span>
            </div>

            <div class="d-flex gap-4 border-bottom py-2">
              <strong>Gender:</strong>
              <span class="text-muted">
                {% if user_info.profile.gender == "M" %} 
                Male 
                {% else %} 
                Female 
                {% endif %}
              </span>
            </div>

            <div class="d-flex gap-4 border-bottom py-2">
              <strong>Age:</strong>
              <span class="text-muted ms-4">{{ user_info.profile.age }}</span>
            </div>
          </div>

          <!-- Friendship status =====================-->
          {% if user_info.friendship_status == 'pending' %}
            <div>
                <form method="post" action="{% url 'contacts_app:cancel_friend_request' user_info.user.id %}">
                {% csrf_token %}
                Friend request: <span style="color: orange;">{{ user_info.friendship_status }}</span>
                <input type="hidden" name="next" value="{{ request.path }}">
                <button class="btn btn-warning mt-3 mb-2 w-100" type="submit">Cancel Request</button>
                </form>
            </div>
          {% elif user_info.friendship_status == 'requested' %}
            <div>
              <span style="color: green;">Sends you a friend request</span>
          
              <div class="btn-group mt-3 mb-2 w-100 gap-2">
                  <form method="post" action="{% url 'contacts_app:accept_request' user_info.request_id %}" style="display: inline-block; width: 50%;">
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ request.path }}">
                      <button class="btn btn-success w-100" type="submit">Accept</button>
                  </form>
                  
                  <form method="post" action="{% url 'contacts_app:reject_request' user_info.request_id %}" style="display: inline-block; width: 50%;">
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ request.path }}">
                      <button class="btn btn-danger w-100" type="submit">Reject</button>
                  </form>
              </div>
            </div>
          {% elif user_info.is_friend %}
            <div class="btn-group mt-3  w-100 gap-2" >
              <form method="POST" style="display: inline-block; width: 50%;">
                {% csrf_token %}
                <button class="btn btn-primary  mb-2 w-100" type="submit" disabled>Send Message</button>
              </form>

              <form method="POST" action="{% url 'contacts_app:remove_friend' user_info.user.id %}" style="display: inline-block; width: 50%;">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button class="btn btn-danger  mb-2 w-100" type="submit">Remove Friend</button>
              </form>
            </div>       

            
           
          {% else %}
            <div>
                <form method="post" action="{% url 'contacts_app:send_request' user_info.user.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="btn btn-primary mt-3 mb-2 w-100" type="submit">Add to Friends</button>
                    
                </form>
            </div>
          {% endif %}
    
          <div class="">
            <a href="{% url 'posts_app:all_posts' %}" class="btn btn-outline-primary w-100">
              Back
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

contacts_app/templates/contacts_app/view_users.html
{% extends "base.html" %}
{% block title %}Users{% endblock %}
{% block content %}

<div class="container mt-4">
  {% if users_info_list %}
    <div class="row">
      {% for user_info in users_info_list %}
        <div class="col-12 col-md-6 col-lg-4 mb-4"> 
          <div class="card shadow-sm h-100">
            <div class="card-body text-center">
              <img
                src="{{ user_info.profile.profile_pic_url }}"
                alt="Profile Picture"
                class="rounded-circle mb-3"
                style="width: 80px; height: 80px; object-fit: cover"
              />
              <h2 class="card-title text-primary mb-0">
                <a style="text-decoration: none;" href="{% url 'contacts_app:view_profile' user_info.user.id %}">{{ user_info.user.username }}</a>
              </h2>

              {% if user_info.friendship_status == 'pending' %}
                <div class="d-flex flex-column">
                  <form method="post" action="{% url 'contacts_app:cancel_friend_request' user_info.user.id %}">
                    {% csrf_token %}
                    <span style="color: orange;">{{user_info.friendship_status}}</span>
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="btn btn-warning mt-3 mb-2 w-100" type="submit">Cancel Request</button>
                  </form>
                </div>
              {% elif user_info.friendship_status == 'requested' %}
                <div>
                  <span style="color: green">Sends you a friend request</span>
                  <div class="d-flex  gap-2 btn-group mt-3 mb-2 w-100">
                    <form method="post" action="{% url 'contacts_app:accept_request' user_info.request_id %}" style="display: inline-block; width: 50%;">
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ request.path }}">
                      <button class="btn btn-success w-100" type="submit">Accept</button>
                    </form>

                    <form method="post" action="{% url 'contacts_app:reject_request' user_info.request_id %}" style="display: inline-block; width: 50%;">
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ request.path }}">
                      <button class="btn btn-danger w-100" type="submit">Reject</button>
                    </form>
                  </div>
                </div>
              {% elif user_info.is_friend %}
              <span style="color: transparent;">....</span>
            
                <div class="d-flex mt-3 mb-2 gap-2 w-100">
                  <form method="POST" class="flex-grow-1">
                    {% csrf_token %}
                    <button class="btn btn-primary w-100" type="submit" disabled>Message</button>
                  </form>
                
                  <form method="POST" action="{% url 'contacts_app:remove_friend' user_info.user.id %}" class="flex-grow-1">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="btn btn-danger w-100" type="submit">Remove</button>
                  </form>
                </div>
                
               
              {% else %}
                <div>
                  <span style="color: transparent;">....</span>
                  <form method="post" action="{% url 'contacts_app:send_request' user_info.user.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="btn btn-primary mt-3 mb-2 w-100" type="submit">Add to Friends</button>
                  </form>
                </div>
              {% endif %}
             
            </div>
          </div>
        </div>
      {% endfor %}
      
    </div>
  {% else %}
    <div class="alert alert-info text-center" role="alert">
      No users found.
    </div>
  {% endif %}
  <div class="text-center my-4">
    <a href="{% url 'posts_app:all_posts' %}" class="btn btn-secondary w-25">
      Back
    </a>
  </div>

  
</div>

{% endblock %}