contacts_app/urls.py
from django.urls import path
from . import views

app_name = 'contacts_app'

urlpatterns = [
    path('view_profile/<int:user_id>', views.view_profile, name='view_profile'),
    path('view_friends', views.view_friends, name='view_friends'),
    path('view_users', views.view_users, name='view_users'),
    path('send_request/<int:user_id>/', views.send_request, name='send_request'),
    path('accept_request/<int:request_id>/', views.accept_request, name='accept_request'),
    path('reject_request/<int:request_id>/', views.reject_request, name='reject_request'),
    path('cancel_friend_request/<int:to_user_id>/', views.cancel_friend_request, name='cancel_friend_request'),
    path('remove_friend/<int:friend_id>/', views.remove_friend, name='remove_friend'),
]

main/urls.py
from .views import *
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
]

posts_app/urls.py
from .  import views
from django.urls import path

app_name = 'posts_app'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('post/<slug:slug>', views.post_page, name = "page"),
    path('my_posts', views.my_posts, name = 'my_posts'),
    path('my_posts/<int:post_id>', views.delete_post, name = 'delete_post'),
    path('new_post', views.new_post, name='new_post'),
    path('my_posts/update/<int:id>', views.update_post, name='update_post'),
    path('posts_commented', views.posts_commented, name='posts_commented'),
    path('update_comment/<int:comment_id>/<slug:slug>', views.update_comment, name='update_comment'),
    path('delete_comment/<int:comment_id>/<slug:slug>', views.delete_comment, name = 'delete_comment'),
    path('like_post/<int:post_id>', views.like_post, name = 'like'),
    path('like_post_commented/<int:post_id>', views.like_post_commented, name = 'like_commented'),
    ]

profile_app/urls.py
from django.urls import path
from . import views

app_name = 'profile_app'

urlpatterns = [
    path('',views.profile_view, name='profile'),
    path('update/',views.update_profile, name='update_profile'),
    path('profile/<str:username>',views.view_others_profile, name='view_others_profile')
]

social_media_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('users_app.urls')),
    path('posts/', include('posts_app.urls')),
    path('profile/', include('profile_app.urls')),
    path('contacts/', include('contacts_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_app/urls.py
from .views import *
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('', index, name='index'),
    path('login/', user_login, name='login'),
    path('register/', user_register, name='register'),
    path('logout/', user_logout, name='logout'),
    path('timeout/', user_timeout, name='timeout')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      rel="stylesheet"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-primary-subtle shadow-sm py-2">
      <div class="container-fluid">
        <a class="navbar-brand fw-bold" href="#">Logo</a>

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link {% if request.resolver_match.url_name == 'all_posts' %}active{% endif %}"
                href="{% url 'posts_app:all_posts' %}"
                >All Posts</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if request.resolver_match.url_name == 'my_posts' %}active{% endif %}"
                href="{% url 'posts_app:my_posts' %}"
                >My Posts</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if request.resolver_match.url_name == 'posts_commented' %}active{% endif %}"
                href="{% url 'posts_app:posts_commented' %}"
                >My Reactions</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if request.resolver_match.url_name == 'profile' %}active{% endif %}"
                href="{% url 'profile_app:profile' %}"
                >My Profile</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'view_friends' %}active{% endif %}" 
              href="{% url 'contacts_app:view_friends' %}">
                Friends{% if friend_requests_count > 0 %} ({{ friend_requests_count }}){% endif %}
            </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'view_users' %}active{% endif %}"
               href="{% url 'contacts_app:view_users' %}">
                Users
              </a>
            </li>

          </ul>

          <div class="d-flex justify-content-between align-items-center gap-3">
            <div class="d-flex gap-2 align-items-center">
              <img
                src="{{ profile.profile_pic.url }}"
                width="40"
                height="40"
                alt="User"
                class="rounded-circle border"
                loading="eager"
              />
              <span class="fw-semibold">{{ user.username }}</span>
            </div>

            <a
              href="{% url 'users:logout' %}"
              class="btn btn-sm btn-danger d-flex align-items-center gap-1"
            >
              <i class="fas fa-sign-out-alt"></i>
              Logout
            </a>
          </div>
        </div>
      </div>
    </nav>

    <div
      class="container align-items-center flex-column gap-2 d-flex justify-content-center mt-4"
    >
      {% block content %} {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/index.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Social Media App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
</head>
<body>

    <div class="container-fluid">
        <div class="image-section" style="background: url('{% static "images/social.png" %}') no-repeat center center/contain; height: 60vh;">
        </div>
    </div>
    
    <div class="container-fluid text-center py-5 bg-primary-subtle">
        <h2 class=" text-primary fw-bold text-shadow-lg">Your Stories, Your Network, Your Way</h2>
        <p class="lead text-muted mb-4">Choose an option to begin your journey</p>
    
        <div class="d-flex justify-content-center">
            <a href="{% url 'users:login' %}" class="btn btn-primary btn-md w-25 me-3 btn-custom">Login</a>
            <a href="{% url 'users:register' %}" class="btn btn-outline-primary btn-md w-25 btn-custom">Register</a>
        </div>
    </div>   

    <div class="container-fluid py-5 bg-light">       
        <div class="text-center mb-4">
            <h2>Our Team</h2>
            <p>Meet the amazing people behind our success</p>
        </div>

        <div class="row row-cols-1 row-cols-md-3 row-cols-lg-5 g-2">

            <div class="col ">
                <div class="card text-center">
                    <img src="media/profile_images/lisa.png" class="card-img-top rounded-circle mx-auto mt-3" alt="Member 1" style="width: 100px; height: 100px">
                    <div class="card-body">
                        <h5 class="card-title">Yamit</h5>
                        <div class="d-flex justify-content-center align-items-center gap-3 pt-2">
                                <a href="https://linkedin.com/in/yamit-a-3b7a97292/" target="_blank" class="text-decoration-none"><i class="bi bi-linkedin fs-5 text-muted"></i></a>

                                <a href="https://github.com/yam91" target="_blank" class="text-decoration-none"> <i class="bi bi-github fs-5 text-muted"></i></a>

                                <a href="https://github.com/" target="_blank" class="text-decoration-none"> <i class="bi bi-folder fs-5 text-muted"></i></a>

                        </div>
                        
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card text-center">
                    <img src="{% static "images/viggo.jpg" %}" class="card-img-top rounded-circle mx-auto mt-3" alt="Member 2" style="width: 100px; height: 100px;">
                    <div class="card-body">
                        <h5 class="card-title">Viggo</h5>
                        <div class="d-flex justify-content-center align-items-center gap-3 pt-2">
                                <a href="https://www.linkedin.com/in/viggo-gustafsson/" target="_blank" class="text-decoration-none"><i class="bi bi-linkedin fs-5 text-muted"></i></a>

                                <a href="https://github.com/ViiGuu" target="_blank" class="text-decoration-none"> <i class="bi bi-github fs-5 text-muted"></i></a>

                                <a href="https://github.com/ViiGuu" target="_blank" class="text-decoration-none"> <i class="bi bi-folder fs-5 text-muted"></i></a>

                        </div>
                        
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card text-center">
                    <img src="{% static "images/profile_pic.jpg" %}" class="card-img-top rounded-circle mx-auto mt-3" alt="Member 3" style="width: 100px; height: 100px;">
                    <div class="card-body">
                        <h5 class="card-title">Usman</h5>
                        <div class="d-flex justify-content-center align-items-center gap-3 pt-2">
                                <a href="https://www.linkedin.com/in/muhammad-usman-78491149/" target="_blank" class="text-decoration-none"><i class="bi bi-linkedin fs-5 text-muted"></i></a>

                                <a href="https://github.com/MuhammadUsmanMushtaq" target="_blank" class="text-decoration-none"> <i class="bi bi-github fs-5 text-muted"></i></a>

                                <a href="https://muhammad-usman.netlify.app/" target="_blank" class="text-decoration-none"> <i class="bi bi-folder fs-5 text-muted"></i></a>

                        </div>
                        
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card text-center">
                    <img src="{% static "images/Ratna_profile_pic.png" %}" class="card-img-top rounded-circle mx-auto mt-3" alt="Member 4" style="width: 100px; height: 100px;">
                    <div class="card-body">
                        <h5 class="card-title">Ratna</h5>
                        <div class="d-flex justify-content-center align-items-center gap-3 pt-2">
                                <a href="https://linkedin.com/in/ratnaprabha-kadam/" target="_blank" class="text-decoration-none"><i class="bi bi-linkedin fs-5 text-muted"></i></a>

                                <a href="https://github.com/RatnaKadam" target="_blank" class="text-decoration-none"> <i class="bi bi-github fs-5 text-muted"></i></a>

                                <a href="https://github.com/" target="_blank" class="text-decoration-none"> <i class="bi bi-folder fs-5 text-muted"></i></a>

                        </div>
                        
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card text-center">
                    <img src="{% static "images/irik_profile_picture.png" %}" class="card-img-top rounded-circle mx-auto mt-3" alt="Member 5" style="width: 100px; height: 100px;">
                    <div class="card-body">
                        <h5 class="card-title">Irik</h5>
                        <div class="d-flex justify-content-center align-items-center gap-3 pt-2">
                                <a href="https://linkedin.com/in/irik-alimbaev" target="_blank" class="text-decoration-none"><i class="bi bi-linkedin fs-5 text-muted"></i></a>

                                <a href="https://github.com/Iralim" target="_blank" class="text-decoration-none"> <i class="bi bi-github fs-5 text-muted"></i></a>

                                <a href="#" target="_blank" class="text-decoration-none"> <i class="bi bi-folder fs-5 text-muted"></i></a>

                        </div>
                        
                    </div>
                </div>
            </div>

        </div>
    </div>
    <footer class="container-fluid bg-primary-subtle text-center text-muted py-3">
        <p>&copy; 2024 SocialMediaApp. All rights reserved.</p>
    </footer>
    
</body>
</html>

templates/login_success.html
{% extends 'base.html' %}
{% block title %} Login succsess {% endblock%}

{% block content %}

<h1>Login success</h1>

{% endblock %}

<!-- think this can be removed? -->