main/urls.py
from .views import *
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
]

posts_app/urls.py
from .  import views
from django.urls import path

app_name = 'posts_app'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('post/<slug:slug>', views.post_page, name = "page"),
    path('my_posts', views.my_posts, name = 'my_posts'),
    path('my_posts/<int:post_id>', views.delete_post, name = 'delete_post'),
    path('new_post', views.new_post, name='new_post'),
    path('my_posts/update/<int:id>', views.update_post, name='update_post'),
    path('posts_commented', views.posts_commented, name='posts_commented'),
    path('update_comment/<int:comment_id>/<slug:slug>', views.update_comment, name='update_comment'),
    path('delete_comment/<int:comment_id>/<slug:slug>', views.delete_comment, name = 'delete_comment'),
    path('like_post/<int:post_id>', views.like_post, name = 'like'),
    path('like_post_commented/<int:post_id>', views.like_post_commented, name = 'like_commented'),
    ]

profile_app/urls.py
from django.urls import path
from . import views

app_name = 'profile_app'

urlpatterns = [
    path('',views.profile_view, name='profile'),
    path('update/',views.update_profile, name='update_profile'),
    path('profile/<str:username>',views.view_others_profile, name='view_others_profile')
]

social_media_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('users_app.urls')),
    path('posts/', include('posts_app.urls')),
    path('profile/', include('profile_app.urls')),
    path('contacts/', include('contacts_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Q

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_pic = models.ImageField(default = 'profile_images/user.png', upload_to='profile_images/',blank=True, null=True)
    gender = models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)
    age = models.IntegerField(default=None)

    @property
    def profile_pic_url(self):
        if self.profile_pic:
            return self.profile_pic.url
        else:
            return f'{settings.MEDIA_URL}profile_images/user.png'
            

    def __str__(self):
        return f"{self.user.username}'s Profile"
    
    @property
    def friends(self):
        from contacts_app.models import Friendship
        return User.objects.filter(
            Q(friendships_as_user1__user2=self.user) | Q(friendships_as_user2__user1=self.user)
        ).distinct()

profile_app/forms.py
from django import forms
from profile_app.models import Profile

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_pic', 'gender', 'age']

        widgets = {
            'profile_pic': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(choices=[('M', 'Male'), ('F', 'Female')], attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'min': 0, 'class': 'form-control'}),
        }

profile_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from profile_app.models import Profile
from profile_app.forms import  ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.models import User


def index(request):
    return render (request,'index.html')

#view own profile
@login_required
def profile_view(request):
    profile = request.user.profile
    return render(request, 'profile_app/profile.html', {'profile': profile})

#update profile
@login_required
def update_profile(request):
    profile = Profile.objects.get(user=request.user)  # Get the profile for the logged-in user
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():                     #validate the updated_form
            form.save()
            messages.success(request, "Your Profile is updated!!")
            return redirect('profile_app:profile')       #redirect to profile page
    else:
        form = ProfileUpdateForm(instance=profile)

    return render(request, 'profile_app/update_profile.html', {'form': form, 'profile':profile})

#view other user's profile
@login_required
def view_others_profile(request, username):
    user = get_object_or_404(User,username=username) # Get the user of the post
    other_profile = Profile.objects.get(user=user)  # Get the profile of user
    return render(request, 'profile_app/view_profile.html', {'profile':other_profile})

profile_app/templates/profile_app/profile.html
{% extends "base.html" %} 
{% block title %}Profile Page{% endblock %} 
{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-body text-center">
          <h2 class="py-4">User Profile</h2>

          <img
            src="{{ profile.profile_pic_url }}"
            alt="Profile Picture"
            class="rounded-circle mb-3"
            style="width: 120px; height: 120px; object-fit: cover"
          />

          <p class="text-muted m-0" style="font-size: 14px">Username</p>
          <h2 class="card-title text-primary mb-0">
            {{ profile.user.username }}
          </h2>

          <div class="text-start py-2">
            <div class="d-flex gap-4 border-bottom pb-2">
              <strong>Joined:</strong>
              <span class="text-muted ms-1"
                >{{ profile.user.date_joined }}</span
              >
            </div>

            <div class="d-flex gap-4 border-bottom py-2">
              <strong>Gender:</strong>
              <span class="text-muted">
                {% if profile.gender == "M" %} 
                Male 
                {% else %} 
                Female 
                {% endif %}
              </span>
            </div>

            <div class="d-flex gap-4 border-bottom py-2">
              <strong>Age:</strong>
              <span class="text-muted ms-4">{{ profile.age }}</span>
            </div>
          </div>

          <a
            href="{% url 'profile_app:update_profile' %}"
            class="btn btn-primary mt-3 mb-2 w-100"
          >
            Update Profile
          </a> 
            <a href="{% url 'posts_app:all_posts' %}" class="btn btn-outline-primary w-100">
              Back
            </a>      
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

profile_app/templates/profile_app/update_profile.html
{% extends "base.html" %} 
{% block title %}Update Profile{% endblock %} 
{% block content %}

<div class="container d-flex justify-content-center align-items-center mt-4">
  <div class="col-md-6 p-4 border rounded shadow-sm">
    <h3 class="text-center mb-4">Update profile</h3>

    <form
      class="d-flex flex-column"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %} 
      <div class="mb-3">
        <label for="id_profile_pic" class="form-label">Profile Picture</label>
        <input
          type="file"
          name="profile_pic"
          id="id_profile_pic"
          class="form-control"
        />
        {% if form.profile_pic.errors %}
        <div class="text-danger small">{{ form.profile_pic.errors }}</div>
        {% endif %}
      </div>
      <div class="mb-3">
        <label for="gender" class="form-label">Gender</label>
        {{ form.gender }} {% if form.gender.errors %}
        <div class="text-danger small">{{ form.gender.errors }}</div>
        {% endif %}
      </div>

      <div class="mb-3">
        <label for="age" class="form-label">Age</label>
        {{ form.age }} 
        {% if form.age.errors %}
        <div class="text-danger small">
        {{ form.age.errors }}
        </div>
        {% endif %}
      </div>

      <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary">Save</button>
        <a
          href="{% url 'posts_app:all_posts' %}"
          class="btn btn-outline-primary mb-4 w-100"
        >
          Cancel
        </a>
      </div>
    </form>
  </div>
</div>

{% endblock %}